SCIENTIFIC_NAMES = {
    "Aardvark": "Orycteropus afer",
    "Aardwolf": "Proteles cristata",
    "Abalone": "Haliotidae",
    "Acacia": "Acacia",
    "Acai": "Euterpe oleracea",
    "Acorn squash": "Cucurbita pepo var. turbinata",
    "Adiantum": "Adiantum",
    "Adélie penguin": "Pygoscelis adeliae",
    "Aeonium": "Aeonium",
    "African bullfrog": "Pyxicephalus adspersus",
    "African elephant": "Loxodonta",
    "African grey parrot": "Psittacus erithacus",
    "African violet": "Streptocarpus sect. Saintpaulia",
    "African wild dog": "Lycaon pictus",
    "Agapanthus": "Agapanthus",
    "Agave": "Agave",
    "Agouti": "Dasyprocta",
    "Air plant": "Tillandsia",
    "Alamanda": "Allamanda",
    "Albatross": "Diomedeidae",
    "Aldabra giant tortoise": "Aldabrachelys gigantea",
    "Alder": "Alnus",
    "Aldrovanda": "Aldrovanda",
    "Alligator": "Alligator",
    "Alligator snapping turtle": "Macrochelys temminckii",
    "Allium": "Allium",
    "Allosaurus": "Allosaurus",
    "Alocasia": "Alocasia",
    "Aloe vera": "Aloe vera",
    "Alpine newt": "Ichthyosaura alpestris",
    "Amargasaurus": "Amargasaurus cazaui",
    "Amaryllis": "Amaryllis",
    "Amazon milk frog": "Trachycephalus resinifictrix",
    "Amazon parrot": "Amazona",
    "Amazon sword plant": "Echinodorus grisebachii",
    "American alligator": "Alligator mississippiensis",
    "American black bear": "Ursus americanus",
    "American crocodile": "Crocodylus acutus",
    "Anaconda": "Eunectes",
    "Andean condor": "Vultur gryphus",
    "Anemone": "Anemone",
    "Angel's trumpet": "Brugmansia",
    "Angelfish": "Pterophyllum",
    "Anglerfish": "Lophiiformes",
    "Anhinga": "Anhinga anhinga",
    "Ankylosaurus": "Ankylosaurus",
    "Anole": "Anolis",
    "Anteater": "Vermilingua",
    "Anthurium": "Anthurium",
    "Anubias": "Anubias",
    "Apatosaurus": "Apatosaurus",
    "Apple": "Malus domestica",
    "Apple tree": "Malus domestica",
    "Apricot": "Prunus armeniaca",
    "Apricot tree": "Prunus armeniaca",
    "Arapaima": "Arapaima",
    "Araucaria": "Araucaria",
    "Archaeopteryx": "Archaeopteryx",
    "Archerfish": "Toxotidae",
    "Arctic fox": "Vulpes lagopus",
    "Areca palm": "Dypsis lutescens",
    "Argentinosaurus": "Argentinosaurus",
    "Arizona bark scorpion": "Centruroides sculpturatus",
    "Armadillo": "Dasypodidae",
    "Armadillo girdled lizard": "Ouroborus cataphractus",
    "Army ant": "Dorylinae",
    "Artichoke": "Cynara cardunculus var. scolymus",
    "Arugula": "Eruca vesicaria subsp. sativa",
    "Ash tree": "Fraxinus",
    "Asian black bear": "Ursus thibetanus",
    "Asian elephant": "Elephas maximus",
    "Asian giant hornet": "Vespa mandarinia",
    "Asparagus": "Asparagus officinalis",
    "Aspen": "Populus sect. Populus",
    "Asplenium": "Asplenium",
    "Assassin bug": "Reduviidae",
    "Aster": "Asteraceae",
    "Astrophytum": "Astrophytum",
    "Atemoya": "Annona × atemoya",
    "Atlas beetle": "Chalcosoma atlas",
    "Atlas moth": "Attacus atlas",
    "Avocado": "Persea americana",
    "Avocado tree": "Persea americana",
    "Avocet": "Recurvirostra",
    "Axis deer": "Axis axis",
    "Axolotl": "Ambystoma mexicanum",
    "Aye-aye": "Daubentonia madagascariensis",
    "Azalea": "Rhododendron",
    "Açaí": "Euterpe oleracea",
    "Baboon": "Papio",
    "Badger": "Mustelidae",
    "Bald eagle": "Haliaeetus leucocephalus",
    "Ball python": "Python regius",
    "Bamboo palm": "Chamaedorea seifrizii",
    "Bamboo shoot": "Bambusoideae",
    "Banana": "Musa",
    "Banded demoiselle": "Calopteryx splendens",
    "Banyan": "Ficus benghalensis",
    "Baobab": "Adansonia",
    "Barbet": "Capitonidae",
    "Barn owl": "Tyto alba",
    "Barnacle": "Cirripedia",
    "Barracuda": "Sphyraena",
    "Barred owl": "Strix varia",
    "Barrel cactus": "Ferocactus",
    "Baryonyx": "Baryonyx",
    "Basil": "Ocimum basilicum",
    "Basilisk lizard": "Basiliscus",
    "Basking shark": "Cetorhinus maximus",
    "Bat-eared fox": "Otocyon megalotis",
    "Bay laurel": "Laurus nobilis",
    "Bay leaf": "Laurus nobilis",
    "Bearded dragon": "Pogona",
    "Bearded vulture": "Gypaetus barbatus",
    "Beaver": "Castor",
    "Bee balm": "Monarda",
    "Bee fly": "Bombyliidae",
    "Bee-eater": "Meropidae",
    "Beech": "Fagus",
    "Beetroot": "Beta vulgaris subsp. vulgaris Conditiva Group",
    "Begonia": "Begonia",
    "Bell pepper": "Capsicum annuum",
    "Beluga whale": "Delphinapterus leucas",
    "Bergamot orange": "Citrus ×bergamia",
    "Betta": "Betta",
    "Binturong": "Arctictis binturong",
    "Birch": "Betula",
    "Bird of paradise (plant)": "Strelitzia",
    "Bird's-nest fern": "Asplenium nidus",
    "Bird-of-paradise": "Paradisaeidae",
    "Birdwing butterfly": "Ornithoptera",
    "Bishop's cap cactus": "Astrophytum myriostigma",
    "Bison": "Bison",
    "Bitter melon": "Momordica charantia",
    "Black caiman": "Melanosuchus niger",
    "Black kite": "Milvus migrans",
    "Black mamba": "Dendroaspis polylepis",
    "Black rhinoceros": "Diceros bicornis",
    "Black widow spider": "Latrodectus",
    "Black-eyed Susan": "Rudbeckia hirta",
    "Black-eyed pea": "Vigna unguiculata subsp. unguiculata",
    "Black-footed cat": "Felis nigripes",
    "Blackberry": "Rubus sect. Rubus",
    "Blackbird": "Turdus merula",
    "Blackcurrant": "Ribes nigrum",
    "Blacktip reef shark": "Carcharhinus melanopterus",
    "Bladderwort": "Utricularia",
    "Blanket octopus": "Tremoctopus",
    "Bleeding heart (plant)": "Lamprocapnos spectabilis",
    "Blister beetle": "Meloidae",
    "Blood orange": "Citrus × sinensis",
    "Blue dasher": "Pachydiplax longipennis",
    "Blue jay": "Cyanocitta cristata",
    "Blue morpho": "Morpho",
    "Blue poison dart frog": "Dendrobates azureus",
    "Blue shark": "Prionace glauca",
    "Blue whale": "Balaenoptera musculus",
    "Blue-and-yellow macaw": "Ara ararauna",
    "Blue-ringed octopus": "Hapalochlaena",
    "Blue-tongued skink": "Tiliqua",
    "Bluebell": "Hyacinthoides non-scripta",
    "Blueberry": "Vaccinium sect. Cyanococcus",
    "Bluebottle fly": "Calliphora vomitoria",
    "Boa constrictor": "Boa constrictor",
    "Boab": "Adansonia gregorii",
    "Bobcat": "Lynx rufus",
    "Bok choy": "Brassica rapa subsp. chinensis",
    "Bombardier beetle": "Brachininae",
    "Bonefish": "Albula vulpes",
    "Bongo (antelope)": "Tragelaphus eurycerus",
    "Bonobo": "Pan paniscus",
    "Booby": "Sula",
    "Boomslang": "Dispholidus typus",
    "Boston fern": "Nephrolepis exaltata",
    "Bougainvillea": "Bougainvillea",
    "Bowhead whale": "Balaena mysticetus",
    "Box jellyfish": "Cubozoa",
    "Box turtle": "Terrapene",
    "Boysenberry": "Rubus ursinus × idaeus",
    "Brachiosaurus": "Brachiosaurus",
    "Bracken": "Pteridium",
    "Brahminy kite": "Haliastur indus",
    "Brain coral": "Diploria",
    "Brazilian wandering spider": "Phoneutria",
    "Breadfruit": "Artocarpus altilis",
    "Bristlecone pine": "Pinus subsect. Balfourianae",
    "Brittle star": "Ophiuroidea",
    "Broad bean": "Vicia faba",
    "Brocchinia reducta": "Brocchinia reducta",
    "Broccoli": "Brassica oleracea var. italica",
    "Broccolini": "Brassica oleracea var. italica × alboglabra",
    "Bromeliad": "Bromeliaceae",
    "Brontosaurus": "Brontosaurus",
    "Broomrape": "Orobanche",
    "Brown bear": "Ursus arctos",
    "Brown recluse spider": "Loxosceles reclusa",
    "Brussels sprout": "Brassica oleracea var. gemmifera",
    "Buddha's hand": "Citrus medica var. sarcodactylis",
    "Budgerigar": "Melopsittacus undulatus",
    "Bull frog": "Lithobates catesbeianus",
    "Bull shark": "Carcharhinus leucas",
    "Bullet ant": "Paraponera clavata",
    "Bullfinch": "Pyrrhula pyrrhula",
    "Bumblebee": "Bombus",
    "Bumblebee bat": "Craseonycteris thonglongyai",
    "Bunting": "Emberizidae",
    "Burmese python": "Python bivittatus",
    "Burro's tail": "Sedum morganianum",
    "Burrowing owl": "Athene cunicularia",
    "Bush dog": "Speothos venaticus",
    "Bushbuck": "Tragelaphus scriptus",
    "Bushmaster": "Lachesis",
    "Buttercup": "Ranunculus",
    "Butterflyfish": "Chaetodontidae",
    "Butternut squash": "Cucurbita moschata",
    "Butterwort": "Pinguicula",
    "Button mushroom": "Agaricus bisporus",
    "Byblis": "Byblis",
    "Cabbage": "Brassica oleracea var. capitata",
    "Cabbage white butterfly": "Pieris rapae",
    "Cacomistle": "Bassariscus sumichrasti",
    "Cactus": "Cactaceae",
    "Cactus fruit": "Opuntia",
    "Caecilian": "Gymnophiona",
    "Caiman": "Caima",
    "Caladium": "Caladium",
    "Calamansi": "×Citrofortunella microcarpa",
    "Calathea": "Calathea",
    "Calendula": "Calendula",
    "California condor": "Gymnogyps californianus",
    "Camarasaurus": "Camarasaurus",
    "Camel spider": "Solifugae",
    "Camellia": "Camellia",
    "Cane toad": "Rhinella marina",
    "Cannonball tree": "Couroupita guianensis",
    "Cantaloupe": "Cucumis melo var. cantalupensis",
    "Caper": "Capparis spinosa",
    "Capuchin monkey": "Cebinae",
    "Capybara": "Hydrochoerus hydrochaeris",
    "Caracal": "Caracal caracal",
    "Carambola": "Averrhoa carambola",
    "Cardinal (bird)": "Cardinalis cardinalis",
    "Cardoon": "Cynara cardunculus",
    "Caribou": "Rangifer tarandus",
    "Carnation": "Dianthus caryophyllus",
    "Carnotaurus": "Carnotaurus",
    "Carolina Reaper": "Capsicum chinense 'Carolina Reaper'",
    "Carpenter ant": "Camponotus",
    "Carpenter bee": "Xylocopa",
    "Carrot": "Daucus carota subsp. sativus",
    "Casaba melon": "Cucumis melo var. inodorus",
    "Cassava": "Manihot esculenta",
    "Cassowary": "Casuarius",
    "Cast iron plant": "Aspidistra elatior",
    "Castor oil plant": "Ricinus communis",
    "Catbird": "Dumetella carolinensis",
    "Cauliflower": "Brassica oleracea var. botrytis",
    "Cave salamander": "Eurycea lucifuga",
    "Cayenne pepper": "Capsicum annuum var. acuminatum",
    "Cecropia moth": "Hyalophora cecropia",
    "Cedar": "Cedrus",
    "Celeriac": "Apium graveolens var. rapaceum",
    "Celery": "Apium graveolens",
    "Celosia": "Celosia",
    "Centipede": "Chilopoda",
    "Centrosaurus": "Centrosaurus",
    "Cephalotus": "Cephalotus",
    "Ceratosaurus": "Ceratosaurus",
    "Cereus": "Cereus",
    "Ceropegia": "Ceropegia",
    "Chaffinch": "Fringilla coelebs",
    "Chain of hearts": "Ceropegia woodii",
    "Chambered nautilus": "Nautilus pompilius",
    "Chameleon": "Chamaeleonidae",
    "Chamois": "Rupicapra rupicapra",
    "Chamomile": "Matricaria chamomilla",
    "Chanterelle": "Cantharellus cibarius",
    "Chasmosaurus": "Chasmosaurus",
    "Chayote": "Sicyos edulis",
    "Cheetah": "Acinonyx jubatus",
    "Cherimoya": "Annona cherimola",
    "Cherry": "Prunus avium",
    "Cherry blossom": "Prunus serrulata",
    "Cherry tree": "Prunus",
    "Chervil": "Anthriscus cerefolium",
    "Chestnut": "Castanea",
    "Chickpea": "Cicer arietinum",
    "Chicory": "Cichorium intybus",
    "Chili pepper": "Capsicum",
    "Chimpanzee": "Pan troglodytes",
    "Chinchilla": "Chinchilla",
    "Chinese alligator": "Alligator sinensis",
    "Chinese cabbage": "Brassica rapa subsp. pekinensis",
    "Chinese evergreen": "Aglaonema",
    "Chinese giant salamander": "Andrias davidianus",
    "Chinstrap penguin": "Pygoscelis antarcticus",
    "Chipmunk": "Tamiini",
    "Chive": "Allium schoenoprasum",
    "Cholla": "Cylindropuntia",
    "Christmas cactus": "Schlumbergera",
    "Christmas tree worm": "Spirobranchus giganteus",
    "Chrysanthemum": "Chrysanthemum",
    "Chuckwalla": "Sauromalus",
    "Cicada": "Cicadoidea",
    "Cilantro": "Coriandrum sativum",
    "Cinnabar moth": "Tyria jacobaeae",
    "Cinnamon fern": "Osmundastrum cinnamomeum",
    "Citrus": "Citrus",
    "Civet": "Viverridae",
    "Cleaner shrimp": "Lysmata amboinensis",
    "Clematis": "Clematis",
    "Clementine": "Citrus ×clementina",
    "Click beetle": "Elateridae",
    "Cloudberry": "Rubus chamaemorus",
    "Clouded leopard": "Neofelis nebulosa",
    "Clouded yellow butterfly": "Colias croceus",
    "Clover": "Trifolium",
    "Clownfish": "Amphiprioninae",
    "Club moss": "Lycopodiopsida",
    "Coast redwood": "Sequoia sempervirens",
    "Coati": "Nasua",
    "Cobra": "Naja",
    "Cock-of-the-rock": "Rupicola",
    "Cockatiel": "Nymphicus hollandicus",
    "Cockatoo": "Cacatuidae",
    "Cocoa tree": "Theobroma cacao",
    "Coconut": "Cocos nucifera",
    "Coconut crab": "Birgus latro",
    "Coconut palm": "Cocos nucifera",
    "Coelacanth": "Coelacanthiformes",
    "Coelacanth (plant)": "Zamia",
    "Coelophysis": "Coelophysis",
    "Coleus": "Coleus",
    "Collard greens": "Brassica oleracea var. viridis",
    "Collared lizard": "Crotaphytus collaris",
    "Colobus monkey": "Colobus",
    "Colocasia": "Colocasia",
    "Colossal squid": "Mesonychoteuthis hamiltoni",
    "Columbine": "Aquilegia",
    "Comb jelly": "Ctenophora",
    "Comet moth": "Argema mittrei",
    "Comma butterfly": "Polygonia c-album",
    "Common darter": "Sympetrum striolatum",
    "Common toad": "Bufo bufo",
    "Compsognathus": "Compsognathus",
    "Cone snail": "Conidae",
    "Coneflower": "Echinacea",
    "Cookiecutter shark": "Isistius brasiliensis",
    "Cooper's hawk": "Accipiter cooperii",
    "Copperhead (snake)": "Agkistrodon contortrix",
    "Coral": "Anthozoa",
    "Coral snake": "Micrurus",
    "Cormorant": "Phalacrocoracidae",
    "Corn": "Zea mays",
    "Corn snake": "Pantherophis guttatus",
    "Cornflower": "Centaurea cyanus",
    "Corpse flower": "Amorphophallus titanum",
    "Corythosaurus": "Corythosaurus",
    "Cosmos": "Cosmos",
    "Cotinga": "Cotingidae",
    "Cottonmouth": "Agkistrodon piscivorus",
    "Cougar": "Puma concolor",
    "Cowslip": "Primula veris",
    "Coyote": "Canis latrans",
    "Coypu": "Myocastor coypus",
    "Crab spider": "Thomisidae",
    "Cranberry": "Vaccinium subg. Oxycoccus",
    "Crane (bird)": "Gruidae",
    "Crane fly": "Tipuloidea",
    "Cricket (insect)": "Gryllidae",
    "Crocodile": "Crocodylidae",
    "Crocosmia": "Crocosmia",
    "Crocus": "Crocus",
    "Crossbill": "Loxia",
    "Croton (plant)": "Croton",
    "Crow": "Corvus",
    "Crown of thorns": "Euphorbia milii",
    "Crown-of-thorns starfish": "Acanthaster planci",
    "Crowned eagle": "Stephanoaetus coronatus",
    "Cuckoo": "Cuculidae",
    "Cucumber": "Cucumis sativus",
    "Curlew": "Numenius",
    "Currant": "Ribes",
    "Curry leaf": "Murraya koenigii",
    "Cushion moss": "Leucobryum glaucum",
    "Cuttlefish": "Sepiidae",
    "Cycad": "Cycadales",
    "Cyclamen": "Cyclamen",
    "Cypress": "Cupressus",
    "Daffodil": "Narcissus",
    "Dahlia": "Dahlia",
    "Daikon": "Raphanus sativus subsp. acanthiformis",
    "Daisy": "Bellis perennis",
    "Damselfly": "Zygoptera",
    "Dandelion": "Taraxacum",
    "Darlingtonia californica": "Darlingtonia californica",
    "Darwin's frog": "Rhinoderma darwinii",
    "Date (fruit)": "Phoenix dactylifera",
    "Date palm": "Phoenix dactylifera",
    "Dawn redwood": "Metasequoia glyptostroboides",
    "Day gecko": "Phelsuma",
    "Dead leaf mantis": "Deroplatys desiccata",
    "Deadly nightshade": "Atropa belladonna",
    "Death adder": "Acanthophis",
    "Death's-head hawkmoth": "Acherontia",
    "Deathstalker": "Leiurus quinquestriatus",
    "Deathwatch beetle": "Xestobium rufovillosum",
    "Deinonychus": "Deinonychus",
    "Delicata squash": "Cucurbita maxima 'Delicata'",
    "Delphinium": "Delphinium",
    "Dewy pine": "Drosophyllum lusitanicum",
    "Dhole": "Cuon alpinus",
    "Diamondback terrapin": "Malaclemys terrapin",
    "Dianthus": "Dianthus",
    "Dieffenbachia": "Dieffenbachia",
    "Dik-dik": "Madoqua",
    "Dill": "Anethum graveolens",
    "Dilophosaurus": "Dilophosaurus",
    "Dimetrodon": "Dimetrodon",
    "Dimorphodon": "Dimorphodon",
    "Dingo": "Canis familiaris dingo",
    "Diplodocus": "Diplodocus",
    "Dipper": "Cinclus",
    "Discus (fish)": "Symphysodon",
    "Diving beetle": "Dytiscidae",
    "Dodder": "Cuscuta",
    "Dolphin": "Delphinidae",
    "Dormouse": "Gliridae",
    "Douglas fir": "Pseudotsuga menziesii",
    "Dove": "Columbidae",
    "Dracaena": "Dracaena",
    "Dracorex": "Dracorex",
    "Dragon blood tree": "Dracaena cinnabari",
    "Dragon fruit": "Selenicereus undatus",
    "Dragonfly": "Anisoptera",
    "Drosophyllum": "Drosophyllum",
    "Duckweed": "Lemna",
    "Dugong": "Dugong dugon",
    "Dumbo octopus": "Grimpoteuthis",
    "Dung beetle": "Scarabaeinae",
    "Durian": "Durio zibethinus",
    "Durian tree": "Durio zibethinus",
    "Dwarf crocodile": "Osteolaemus tetraspis",
    "Eagle ray": "Myliobatidae",
    "Eagle-owl": "Bubo",
    "Earwig": "Dermaptera",
    "Easter cactus": "Hatiora gaertneri",
    "Eastern brown snake": "Pseudonaja textilis",
    "Eastern newt": "Notophthalmus viridescens",
    "Ebony": "Diospyros",
    "Ebony jewelwing": "Calopteryx maculata",
    "Echeveria": "Echeveria",
    "Echidna": "Tachyglossidae",
    "Echinacea": "Echinacea",
    "Echinopsis": "Echinopsis",
    "Eclectus parrot": "Eclectus roratus",
    "Edamame": "Glycine max",
    "Edelweiss": "Leontopodium nivale",
    "Edmontosaurus": "Edmontosaurus",
    "Eggplant": "Solanum melongena",
    "Egret": "Ardea alba",
    "Einiosaurus": "Einiosaurus",
    "Eland": "Taurotragus",
    "Elasmosaurus": "Elasmosaurus",
    "Elderberry": "Sambucus",
    "Electric eel": "Electrophorus",
    "Electric ray": "Torpediniformes",
    "Elephant seal": "Mirounga",
    "Elf owl": "Micrathene whitneyi",
    "Elk": "Cervus canadensis",
    "Elm": "Ulmus",
    "Elodea": "Elodea",
    "Emerald tree boa": "Corallus caninus",
    "Emperor dragonfly": "Anax imperator",
    "Emperor penguin": "Aptenodytes forsteri",
    "Emperor scorpion": "Pandinus imperator",
    "Emu": "Dromaius novaehollandiae",
    "Endive": "Cichorium endivia",
    "English ivy": "Hedera helix",
    "Enoki mushroom": "Flammulina velutipes",
    "Eucalyptus": "Eucalyptus",
    "Euoplocephalus": "Euoplocephalus",
    "Euphorbia": "Euphorbia",
    "Eurasian lynx": "Lynx lynx",
    "Eyelash viper": "Bothriechis schlegelii",
    "Fallow deer": "Dama",
    "False gharial": "Tomistoma schlegelii",
    "Feather star": "Crinoidea",
    "Feijoa": "Feijoa",
    "Fennec fox": "Vulpes zerda",
    "Fennel": "Foeniculum vulgare",
    "Fer-de-lance": "Bothrops asper",
    "Fern": "Polypodiopsida",
    "Ferocactus": "Ferocactus",
    "Ferret": "Mustela furo",
    "Ficus": "Ficus",
    "Fiddle-leaf fig": "Ficus lyrata",
    "Fiddler crab": "Uca",
    "Fig": "Ficus carica",
    "Fig tree": "Ficus carica",
    "Fin whale": "Balaenoptera physalus",
    "Fir": "Abies",
    "Fire ant": "Solenopsis",
    "Fire salamander": "Salamandra salamandra",
    "Fire-bellied toad": "Bombina",
    "Firefly": "Lampyridae",
    "Firefly squid": "Watasenia scintillans",
    "Fishhook cactus": "Mammillaria",
    "Fishing cat": "Prionailurus viverrinus",
    "Fishing spider": "Dolomedes",
    "Flamboyant cuttlefish": "Metasepia pfefferi",
    "Flame tree": "Delonix regia",
    "Flamingo": "Phoenicopteridae",
    "Flamingo flower": "Anthurium andraeanum",
    "Flowerpecker": "Dicaeidae",
    "Flying fish": "Exocoetidae",
    "Flying fox": "Pteropus",
    "Flying lizard": "Draco",
    "Flying snake": "Chrysopelea",
    "Flying squirrel": "Pteromyini",
    "Forget-me-not": "Myosotis",
    "Forsythia": "Forsythia",
    "Fossa": "Cryptoprocta ferox",
    "Foxglove": "Digitalis",
    "Frangipani": "Plumeria",
    "Freesia": "Freesia",
    "Frigatebird": "Fregata",
    "Frilled-neck lizard": "Chlamydosaurus kingii",
    "Frogfish": "Antennariidae",
    "Fruit bat": "Pteropodidae",
    "Fruit fly": "Drosophila",
    "Fuchsia": "Fuchsia",
    "Fur seal": "Arctocephalinae",
    "Gaboon viper": "Bitis gabonica",
    "Galago": "Galagidae",
    "Galah": "Eolophus roseicapilla",
    "Galia melon": "Cucumis melo var. reticulatus",
    "Gallimimus": "Gallimimus",
    "Galápagos tortoise": "Chelonoidis niger",
    "Gannet": "Morus",
    "Garden spider": "Araneus diadematus",
    "Garden tiger moth": "Arctia caja",
    "Gardenia": "Gardenia",
    "Garlic": "Allium sativum",
    "Garter snake": "Thamnophis",
    "Gasteria": "Gasteria",
    "Gazelle": "Gazella",
    "Gecko": "Gekkonidae",
    "Gelada": "Theropithecus gelada",
    "Genet": "Genetta",
    "Genlisea": "Genlisea",
    "Gentian": "Gentiana",
    "Gentoo penguin": "Pygoscelis papua",
    "Geranium": "Geranium",
    "Gerenuk": "Litocranius walleri",
    "Gharial": "Gavialis gangeticus",
    "Ghost mantis": "Phyllocrania paradoxa",
    "Ghost pepper": "Capsicum chinense 'Bhut Jolokia'",
    "Ghost plant": "Graptopetalum paraguayense",
    "Giant African millipede": "Archispirostreptus gigas",
    "Giant Asian mantis": "Hierodula membranacea",
    "Giant Pacific octopus": "Enteroctopus dofleini",
    "Giant centipede": "Scolopendra gigantea",
    "Giant clam": "Tridacna gigas",
    "Giant cuttlefish": "Sepia apama",
    "Giant kelp": "Macrocystis pyrifera",
    "Giant panda": "Ailuropoda melanoleuca",
    "Giant prickly stick insect": "Extatosoma tiaratum",
    "Giant salamander": "Cryptobranchidae",
    "Giant sequoia": "Sequoiadendron giganteum",
    "Giant squid": "Architeuthis dux",
    "Giant water bug": "Belostomatidae",
    "Giant water lily": "Victoria amazonica",
    "Gibbon": "Hylobatidae",
    "Giganotosaurus": "Giganotosaurus",
    "Gila monster": "Heloderma suspectum",
    "Ginger": "Zingiber officinale",
    "Ginkgo": "Ginkgo",
    "Ginseng": "Panax",
    "Giraffe": "Giraffa",
    "Giraffe weevil": "Trachelophorus giraffa",
    "Gladiolus": "Gladiolus",
    "Glass frog": "Centrolenidae",
    "Glass lizard": "Ophisaurus",
    "Glasswing butterfly": "Greta oto",
    "Goblin shark": "Mitsukurina owstoni",
    "Goji berry": "Lycium barbarum",
    "Golden eagle": "Aquila chrysaetos",
    "Golden lion tamarin": "Leontopithecus rosalia",
    "Golden pheasant": "Chrysolophus pictus",
    "Golden poison frog": "Phyllobates terribilis",
    "Golden silk orb-weaver": "Nephila",
    "Golden toad": "Incilius periglenes",
    "Goldfinch": "Carduelis carduelis",
    "Goliath beetle": "Goliathus",
    "Goliath birdeater": "Theraphosa blondi",
    "Goliath frog": "Conraua goliath",
    "Gooseberry": "Ribes uva-crispa",
    "Gorilla": "Gorilla",
    "Grape": "Vitis vinifera",
    "Grapefruit": "Citrus paradisi",
    "Graptoveria": "× Graptoveria",
    "Grasshopper": "Caelifera",
    "Gray fox": "Urocyon cinereoargenteus",
    "Gray whale": "Eschrichtius robustus",
    "Great blue heron": "Ardea herodias",
    "Great crested newt": "Triturus cristatus",
    "Great grey owl": "Strix nebulosa",
    "Great horned owl": "Bubo virginianus",
    "Great white shark": "Carcharodon carcharias",
    "Green anaconda": "Eunectes murinus",
    "Green bean": "Phaseolus vulgaris",
    "Green iguana": "Iguana iguana",
    "Green mamba": "Dendroaspis viridis",
    "Green sea turtle": "Chelonia mydas",
    "Green tree frog": "Litoria caerulea",
    "Green tree python": "Morelia viridis",
    "Greenland shark": "Somniosus microcephalus",
    "Griffon vulture": "Gyps fulvus",
    "Ground beetle": "Carabidae",
    "Groundhog": "Marmota monax",
    "Grouper": "Epinephelinae",
    "Grouse": "Tetraoninae",
    "Guava": "Psidium guajava",
    "Guava tree": "Psidium guajava",
    "Guillemot": "Uria",
    "Guinea fowl": "Numididae",
    "Guitarfish": "Rhinobatidae",
    "Gull": "Larinae",
    "Guppy": "Poecilia reticulata",
    "Gymnocalycium": "Gymnocalycium",
    "Gyrfalcon": "Falco rusticolus",
    "Habanero": "Capsicum chinense 'Habanero'",
    "Hadrosaurus": "Hadrosaurus",
    "Hairstreak butterfly": "Theclinae",
    "Hammerhead shark": "Sphyrnidae",
    "Harbor seal": "Phoca vitulina",
    "Harebell": "Campanula rotundifolia",
    "Harlequin toad": "Atelopus",
    "Harpy eagle": "Harpia harpyja",
    "Harris's hawk": "Parabuteo unicinctus",
    "Hart's-tongue fern": "Asplenium scolopendrium",
    "Hartebeest": "Alcelaphus buselaphus",
    "Harvestman": "Opiliones",
    "Hawk moth": "Sphingidae",
    "Hawksbill sea turtle": "Eretmochelys imbricata",
    "Haworthia": "Haworthia",
    "Hawthorn": "Crataegus",
    "Hearts of palm": "Euterpe edulis",
    "Heather": "Calluna vulgaris",
    "Hedgehog": "Erinaceinae",
    "Helenium": "Helenium",
    "Heliamphora": "Heliamphora",
    "Heliconia": "Heliconia",
    "Hellbender": "Cryptobranchus alleganiensis",
    "Hemlock": "Conium maculatum",
    "Hemlock (tree)": "Tsuga",
    "Hen and chicks": "Sempervivum tectorum",
    "Hercules beetle": "Dynastes hercules",
    "Hermit crab": "Paguroidea",
    "Heron": "Ardeidae",
    "Herrerasaurus": "Herrerasaurus",
    "Hibiscus": "Hibiscus",
    "Hickory": "Carya",
    "Hippopotamus": "Hippopotamus amphibius",
    "Hoatzin": "Opisthocomus hoazin",
    "Hognose snake": "Heterodon",
    "Holly": "Ilex",
    "Hollyhock": "Alcea rosea",
    "Honeybee": "Apis mellifera",
    "Honeydew melon": "Cucumis melo var. inodorus",
    "Hoopoe": "Upupidae",
    "Hornbeam": "Carpinus",
    "Hornbill": "Bucerotidae",
    "Horned lizard": "Phrynosoma",
    "Horned melon": "Cucumis metuliferus",
    "Hornet": "Vespa",
    "Hornwort (aquarium)": "Ceratophyllum demersum",
    "Hornwort (plant)": "Anthocerotophyta",
    "Horsefly": "Tabanidae",
    "Horseradish": "Armoracia rusticana",
    "Horseshoe bat": "Rhinolophidae",
    "Horseshoe crab": "Limulidae",
    "Horsetail": "Equisetum",
    "Hoverfly": "Syrphidae",
    "Howler monkey": "Alouatta",
    "Hoya": "Hoya",
    "Huayangosaurus": "Huayangosaurus",
    "Huckleberry": "Vaccinium",
    "Humboldt squid": "Dosidicus gigas",
    "Hummingbird": "Trochilidae",
    "Hummingbird hawk-moth": "Macroglossum stellatarum",
    "Humpback whale": "Megaptera novaeangliae",
    "Huntsman spider": "Sparassidae",
    "Hyacinth": "Hyacinthus",
    "Hyacinth macaw": "Anodorhynchus hyacinthinus",
    "Hydrangea": "Hydrangea",
    "Hyena": "Hyaenidae",
    "Hypsilophodon": "Hypsilophodon",
    "Iberian lynx": "Lynx pardinus",
    "Ibex": "Capra ibex",
    "Ibis": "Threskiornithinae",
    "Iceberg lettuce": "Lactuca sativa var. capitata",
    "Ichneumon wasp": "Ichneumonidae",
    "Ichthyosaurus": "Ichthyosaurus",
    "Iguana": "Iguana",
    "Iguanodon": "Iguanodon",
    "Impala": "Aepyceros melampus",
    "Impatiens": "Impatiens",
    "Indian pipe": "Monotropa uniflora",
    "Indian rhinoceros": "Rhinoceros unicornis",
    "Indigo snake": "Drymarchon",
    "Indri": "Indri indri",
    "Io moth": "Automeris io",
    "Iris (plant)": "Iris",
    "Isopod": "Isopoda",
    "Ixora": "Ixora",
    "Jabuticaba": "Plinia cauliflora",
    "Jacamar": "Galbulidae",
    "Jacaranda": "Jacaranda",
    "Jackal": "Canis aureus",
    "Jackdaw": "Coloeus",
    "Jackfruit": "Artocarpus heterophyllus",
    "Jackfruit tree": "Artocarpus heterophyllus",
    "Jade plant": "Crassula ovata",
    "Jaguar": "Panthera onca",
    "Jaguarundi": "Puma yagouaroundi",
    "Jalapeño": "Capsicum annuum 'Jalapeño'",
    "Japanese giant salamander": "Andrias japonicus",
    "Japanese macaque": "Macaca fuscata",
    "Japanese maple": "Acer palmatum",
    "Japanese painted fern": "Athyrium niponicum",
    "Japanese spider crab": "Macrocheira kaempferi",
    "Jasmine": "Jasminum",
    "Java fern": "Microsorum pteropus",
    "Java moss": "Taxiphyllum barbieri",
    "Javan rhinoceros": "Rhinoceros sondaicus",
    "Jay": "Garrulus glandarius",
    "Jellyfish": "Scyphozoa",
    "Jewel beetle": "Buprestidae",
    "Jicama": "Pachyrhizus erosus",
    "Joshua tree": "Yucca brevifolia",
    "Jujube": "Ziziphus jujuba",
    "Jumping spider": "Salticidae",
    "Juniper": "Juniperus",
    "Kabocha": "Cucurbita maxima",
    "Kai-lan": "Brassica oleracea var. alboglabra",
    "Kakapo": "Strigops habroptila",
    "Kalanchoe": "Kalanchoe",
    "Kale": "Brassica oleracea var. sabellica",
    "Kangaroo": "Macropodidae",
    "Kapok": "Ceiba pentandra",
    "Katydid": "Tettigoniidae",
    "Kauri": "Agathis australis",
    "Kea": "Nestor notabilis",
    "Kelp": "Laminariales",
    "Kentrosaurus": "Kentrosaurus",
    "Kestrel": "Falco tinnunculus",
    "King cobra": "Ophiophagus hannah",
    "King crab": "Lithodidae",
    "King penguin": "Aptenodytes patagonicus",
    "King snake": "Lampropeltis",
    "King trumpet mushroom": "Pleurotus eryngii",
    "King vulture": "Sarcoramphus papa",
    "Kingfisher": "Alcedinidae",
    "Kinkajou": "Potos flavus",
    "Kit fox": "Vulpes macrotis",
    "Kiwi (bird)": "Apteryx",
    "Kiwifruit": "Actinidia deliciosa",
    "Koala": "Phascolarctos cinereus",
    "Kohlrabi": "Brassica oleracea var. gongylodes",
    "Kombu": "Saccharina japonica",
    "Komodo dragon": "Varanus komodoensis",
    "Kookaburra": "Dacelo",
    "Krill": "Euphausiacea",
    "Kronosaurus": "Kronosaurus",
    "Kudu": "Tragelaphus strepsiceros",
    "Kumquat": "citrus fruit",
    "Lady fern": "Athyrium filix-femina",
    "Ladybug": "Coccinellidae",
    "Lamb's lettuce": "Valerianella locusta",
    "Lambeosaurus": "Lambeosaurus",
    "Lantana": "Lantana",
    "Lanternfish": "Myctophidae",
    "Lanternfly": "Fulgoridae",
    "Larch": "Larix",
    "Laurel": "Laurus",
    "Lavender": "Lavandula",
    "Leaf insect": "Phylliidae",
    "Leaf-tailed gecko": "Uroplatus",
    "Leafcutter ant": "Atta",
    "Leafcutter bee": "Megachile",
    "Leafhopper": "Cicadellidae",
    "Leafy seadragon": "Phycodurus eques",
    "Leatherback sea turtle": "Dermochelys coriacea",
    "Leek": "Allium ampeloprasum",
    "Lemon": "Citrus × limon",
    "Lemon tree": "Citrus × limon",
    "Lemongrass": "Cymbopogon",
    "Lemur": "Lemuroidea",
    "Lentil": "Lens culinaris",
    "Leopard": "Panthera pardus",
    "Leopard frog": "Lithobates pipiens",
    "Leopard gecko": "Eublepharis macularius",
    "Leopard seal": "Hydrurga leptonyx",
    "Leopard shark": "Triakis semifasciata",
    "Lettuce": "Lactuca sativa",
    "Lichen": "Lichenes",
    "Lily": "Lilium",
    "Lima bean": "Phaseolus lunatus",
    "Lime (fruit)": "Citrus × aurantiifolia",
    "Lime tree": "Citrus × aurantiifolia",
    "Linden": "Tilia",
    "Lingonberry": "Vaccinium vitis-idaea",
    "Linnet": "Linaria cannabina",
    "Lion": "Panthera leo",
    "Lion's mane jellyfish": "Cyanea capillata",
    "Lion's mane mushroom": "Hericium erinaceus",
    "Lionfish": "Pterois",
    "Liopleurodon": "Liopleurodon",
    "Lithops": "Lithops",
    "Little blue penguin": "Eudyptula minor",
    "Live oak": "Quercus virginiana",
    "Liverwort": "Marchantiophyta",
    "Lobster": "Nephropidae",
    "Locust": "Acrididae",
    "Loggerhead sea turtle": "Caretta caretta",
    "Long-eared bat": "Plecotus",
    "Long-eared owl": "Asio otus",
    "Longan": "Dimocarpus longan",
    "Longhorn beetle": "Cerambycidae",
    "Loon": "Gavia",
    "Loquat": "Eriobotrya japonica",
    "Lorikeet": "Loriinae",
    "Lotus": "Nelumbo",
    "Lotus root": "Nelumbo nucifera",
    "Lovebird": "Agapornis",
    "Luffa": "Luffa",
    "Luna moth": "Actias luna",
    "Lupinus": "Lupinus",
    "Lychee": "Litchi chinensis",
    "Lychee tree": "Litchi chinensis",
    "Lynx": "Lynx",
    "Macaroni penguin": "Eudyptes chrysolophus",
    "Macaw": "Ara",
    "Magnolia": "Magnolia",
    "Magpie": "Pica pica",
    "Mahi-mahi": "Coryphaena hippurus",
    "Mahogany": "Swietenia",
    "Maiasaura": "Maiasaura",
    "Maidenhair fern": "Adiantum",
    "Maitake": "Grifola frondosa",
    "Mako shark": "Isurus oxyrinchus",
    "Mamenchisaurus": "Mamenchisaurus",
    "Mammillaria": "Mammillaria",
    "Manakin": "Pipridae",
    "Manatee": "Trichechus",
    "Manchineel": "Hippomane mancinella",
    "Mandarin fish": "Synchiropus splendidus",
    "Mandarin orange": "Citrus reticulata",
    "Mandrill": "Mandrillus sphinx",
    "Maned wolf": "Chrysocyon brachyurus",
    "Mango": "Mangifera indica",
    "Mango tree": "Mangifera indica",
    "Mangosteen": "Garcinia mangostana",
    "Mangrove": "Rhizophora",
    "Mangrove snake": "Boiga dendrophila",
    "Manta ray": "Manta",
    "Mantella": "Mantella",
    "Mantis shrimp": "Stomatopoda",
    "Maple": "Acer",
    "Mara": "Dolichotis",
    "Maranta": "Maranta",
    "Marbled newt": "Triturus marmoratus",
    "Margay": "Leopardus wiedii",
    "Marigold": "Tagetes",
    "Marine iguana": "Amblyrhynchus cristatus",
    "Marjoram": "Origanum majorana",
    "Markhor": "Capra falconeri",
    "Marlin": "Istiophoridae",
    "Marmot": "Marmota",
    "Marsh marigold": "Caltha palustris",
    "Martial eagle": "Polemaetus bellicosus",
    "Martin (bird)": "Hirundinidae",
    "Mason bee": "Osmia",
    "Mata mata": "Chelus fimbriatus",
    "Matsutake": "Tricholoma matsutake",
    "Meadowsweet": "Filipendula ulmaria",
    "Medlar": "Mespilus germanica",
    "Meerkat": "Suricata suricatta",
    "Megalania": "Varanus priscus",
    "Megalodon": "Carcharocles megalodon",
    "Megalosaurus": "Megalosaurus",
    "Megamouth shark": "Megachasma pelagios",
    "Merlin (bird)": "Falco columbarius",
    "Methuselah (tree)": "Pinus longaeva",
    "Mexican beaded lizard": "Heloderma horridum",
    "Mexican red-knee tarantula": "Brachypelma hamorii",
    "Microraptor": "Microraptor",
    "Midwife toad": "Alytes",
    "Milk snake": "Lampropeltis triangulum",
    "Millipede": "Diplopoda",
    "Mimic octopus": "Thaumoctopus mimicus",
    "Mimosa pudica": "Mimosa pudica",
    "Mimosa tree": "Albizia julibrissin",
    "Mink": "Lutreola",
    "Minke whale": "Balaenoptera acutorostrata",
    "Minmi (dinosaur)": "Minmi",
    "Mint": "Mentha",
    "Miracle fruit": "Synsepalum dulcificum",
    "Mistletoe": "Viscum album",
    "Mizuna": "Brassica rapa subsp. nipposinica",
    "Mockingbird": "Mimus polyglottos",
    "Mole cricket": "Gryllotalpidae",
    "Monarch butterfly": "Danaus plexippus",
    "Mongoose": "Herpestidae",
    "Monitor lizard": "Varanus",
    "Monkey puzzle tree": "Araucaria araucana",
    "Monkshood": "Aconitum",
    "Monstera": "Monstera",
    "Monterey cypress": "Hesperocyparis macrocarpa",
    "Moon cactus": "Gymnocalycium mihanovichii",
    "Moon jellyfish": "Aurelia aurita",
    "Moonflower": "Ipomoea alba",
    "Moose": "Alces alces",
    "Moray eel": "Muraenidae",
    "Morel": "Morchella",
    "Moringa": "Moringa oleifera",
    "Morning glory": "Ipomoea",
    "Mosasaurus": "Mosasaurus",
    "Moth orchid": "Phalaenopsis",
    "Motmot": "Momotidae",
    "Mouflon": "Ovis gmelini",
    "Mud dauber": "Sceliphron",
    "Mudpuppy": "Necturus maculosus",
    "Mudskipper": "Oxudercinae",
    "Mulberry": "Morus",
    "Muntjac": "Muntiacus",
    "Muscari": "Muscari",
    "Musk ox": "Ovibos moschatus",
    "Mustard greens": "Brassica juncea",
    "Muttaburrasaurus": "Muttaburrasaurus",
    "Narwhal": "Monodon monoceros",
    "Natterjack toad": "Epidalea calamita",
    "Nautilus": "Nautilidae",
    "Nectarine": "Prunus persica var. nucipersica",
    "Neem tree": "Azadirachta indica",
    "Nepenthes": "Nepenthes",
    "Nigersaurus": "Nigersaurus taqueti",
    "Nightingale": "Luscinia megarhynchos",
    "Nile crocodile": "Crocodylus niloticus",
    "Nile monitor": "Varanus niloticus",
    "Nodosaurus": "Nodosaurus",
    "Norfolk Island pine": "Araucaria heterophylla",
    "Nori": "Pyropia",
    "Northern goshawk": "Accipiter gentilis",
    "Northern saw-whet owl": "Aegolius acadicus",
    "Nudibranch": "Nudibranchia",
    "Numbat": "Myrmecobius fasciatus",
    "Nurse shark": "Ginglymostoma cirratum",
    "Nuthatch": "Sitta",
    "Nyala": "Tragelaphus angasii",
    "Oak": "Quercus",
    "Oarfish": "Regalecidae",
    "Ocelot": "Leopardus pardalis",
    "Octopus": "Octopoda",
    "Ogre-faced spider": "Deinopis",
    "Okapi": "Okapia johnstoni",
    "Okra": "Abelmoschus esculentus",
    "Old man cactus": "Cephalocereus senilis",
    "Oleander": "Nerium oleander",
    "Olive": "Olea europaea",
    "Olive tree": "Olea europaea",
    "Olm": "Proteus anguinus",
    "Onion": "Allium cepa",
    "Opossum": "Didelphidae",
    "Opuntia": "Opuntia",
    "Orange (fruit)": "Citrus × sinensis",
    "Orange tree": "Citrus × sinensis",
    "Orangutan": "Pongo",
    "Orca": "Orcinus orca",
    "Orchid": "Orchidaceae",
    "Orchid bee": "Euglossini",
    "Orchid mantis": "Hymenopus coronatus",
    "Oregano": "Origanum vulgare",
    "Organ pipe cactus": "Stenocereus thurberi",
    "Oriental fire-bellied toad": "Bombina orientalis",
    "Oriole": "Oriolidae",
    "Oryx": "Oryx",
    "Oscar (fish)": "Astronotus ocellatus",
    "Osprey": "Pandion haliaetus",
    "Ostrich": "Struthio",
    "Ostrich fern": "Matteuccia struthiopteris",
    "Otter": "Lutrinae",
    "Oviraptor": "Oviraptor",
    "Owl butterfly": "Caligo",
    "Oxeye daisy": "Leucanthemum vulgare",
    "Oyster mushroom": "Pleurotus ostreatus",
    "Oystercatcher": "Haematopus",
    "Pac-Man frog": "Ceratophrys ornata",
    "Pachycephalosaurus": "Pachycephalosaurus",
    "Pachyphytum": "Pachyphytum",
    "Pachyrhinosaurus": "Pachyrhinosaurus",
    "Painted lady (butterfly)": "Vanessa cardui",
    "Painted turtle": "Chrysemys picta",
    "Pallas's cat": "Otocolobus manul",
    "Palm tree": "Arecaceae",
    "Palmate newt": "Lissotriton helveticus",
    "Panda plant": "Kalanchoe tomentosa",
    "Pangolin": "Pholidota",
    "Pansy": "Viola ×wittrockiana",
    "Papaya": "Carica papaya",
    "Papaya tree": "Carica papaya",
    "Paper wasp": "Polistes",
    "Papyrus": "Cyperus papyrus",
    "Parasaurolophus": "Parasaurolophus",
    "Parlor palm": "Chamaedorea elegans",
    "Parrot": "Psittaciformes",
    "Parrotfish": "Scaridae",
    "Parsley": "Petroselinum crispum",
    "Parsnip": "Pastinaca sativa",
    "Partridge": "Perdix perdix",
    "Passion fruit": "Passiflora edulis",
    "Passionflower": "Passiflora",
    "Patagotitan": "Patagotitan",
    "Pea": "Pisum sativum",
    "Peace lily": "Spathiphyllum",
    "Peach": "Prunus persica",
    "Peach tree": "Prunus persica",
    "Peacock": "Pavo cristatus",
    "Peacock butterfly": "Aglais io",
    "Peacock spider": "Maratus",
    "Pear": "Pyrus",
    "Pear tree": "Pyrus communis",
    "Peat moss": "Sphagnum",
    "Pelican": "Pelecanus",
    "Peony": "Paeonia",
    "Peperomia": "Peperomia",
    "Peppered moth": "Biston betularia",
    "Peregrine falcon": "Falco peregrinus",
    "Pereskia": "Pereskia",
    "Periodical cicada": "Magicicada",
    "Persimmon": "Diospyros kaki",
    "Persimmon tree": "Diospyros kaki",
    "Petrel": "Procellariidae",
    "Petunia": "Petunia",
    "Peyote": "Lophophora williamsii",
    "Pheasant": "Phasianus colchicus",
    "Philippine eagle": "Pithecophaga jefferyi",
    "Philodendron": "Philodendron",
    "Phlox": "Phlox",
    "Pigeon": "Columba livia",
    "Pika": "Ochotona",
    "Pilea peperomioides": "Pilea peperomioides",
    "Pill millipede": "Oniscomorpha",
    "Pilot whale": "Globicephala",
    "Pine": "Pinus",
    "Pine marten": "Martes martes",
    "Pineapple": "Ananas comosus",
    "Pipefish": "Syngnathinae",
    "Pipit": "Anthus",
    "Piranha": "Pygocentrus",
    "Pistol shrimp": "Alpheidae",
    "Pit viper": "Crotalinae",
    "Pitcher plant": "Nepenthes",
    "Plantain": "Musa × paradisiaca",
    "Planthopper": "Fulgoroidea",
    "Platypus": "Ornithorhynchus anatinus",
    "Plesiosauria": "Plesiosauria",
    "Plover": "Charadriinae",
    "Plum": "Prunus domestica",
    "Plum tree": "Prunus domestica",
    "Plumeria": "Plumeria",
    "Poison dart frog": "Dendrobatidae",
    "Poison frog": "Dendrobatidae",
    "Polacanthus": "Polacanthus",
    "Polar bear": "Ursus maritimus",
    "Polyphemus moth": "Antheraea polyphemus",
    "Polypody": "Polypodium",
    "Pomegranate": "Punica granatum",
    "Pomegranate tree": "Punica granatum",
    "Pomelo": "Citrus maxima",
    "Ponytail palm": "Beaucarnea recurvata",
    "Poplar": "Populus",
    "Poppy": "Papaver",
    "Porcini": "Boletus edulis",
    "Porcupine": "Erethizontidae",
    "Portobello mushroom": "Agaricus bisporus",
    "Portuguese man o' war": "Physalia physalis",
    "Potato": "Solanum tuberosum",
    "Pothos": "Epipremnum aureum",
    "Prairie dog": "Cynomys",
    "Praying mantis": "Mantodea",
    "Prickly pear": "Opuntia",
    "Prickly pear fruit": "Opuntia ficus-indica",
    "Primrose": "Primula",
    "Proboscis monkey": "Nasalis larvatus",
    "Pronghorn": "Antilocapra americana",
    "Protea": "Protea",
    "Protoceratops": "Protoceratops",
    "Pseudoscorpion": "Pseudoscorpiones",
    "Psittacosaurus": "Psittacosaurus",
    "Ptarmigan": "Lagopus",
    "Pteranodon": "Pteranodon",
    "Pterodactylus": "Pterodactylus",
    "Pudu": "Pudu",
    "Puff adder": "Bitis arietans",
    "Pufferfish": "Tetraodontidae",
    "Puffin": "Fratercula",
    "Pumpkin": "Cucurbita pepo",
    "Purple frog": "Nasikabatrachus sahyadrensis",
    "Purslane": "Portulaca oleracea",
    "Quail": "Coturnix",
    "Quetzal": "Pharomachrus mocinno",
    "Quetzalcoatlus": "Quetzalcoatlus",
    "Quince": "Cydonia oblonga",
    "Quokka": "Setonix brachyurus",
    "Raccoon": "Procyon lotor",
    "Raccoon dog": "Nyctereutes procyonoides",
    "Radicchio": "Cichorium intybus var. foliosum",
    "Radish": "Raphanus sativus",
    "Rafflesia": "Rafflesia",
    "Ragged robin": "Silene flos-cuculi",
    "Rain frog": "Breviceps",
    "Rainbow boa": "Epicrates cenchria",
    "Rainbow plant": "Byblis",
    "Rambutan": "Nephelium lappaceum",
    "Ramp (plant)": "Allium tricoccum",
    "Ranunculus": "Ranunculus",
    "Rapini": "Brassica rapa subsp. sylvestris",
    "Raspberry": "Rubus idaeus",
    "Rat snake": "Pantherophis",
    "Rattlesnake": "Crotalus",
    "Raven": "Corvus corax",
    "Razorbill": "Alca torda",
    "Rebutia": "Rebutia",
    "Red admiral (butterfly)": "Vanessa atalanta",
    "Red cabbage": "Brassica oleracea var. capitata f. rubra",
    "Red campion": "Silene dioica",
    "Red deer": "Cervus elaphus",
    "Red fox": "Vulpes vulpes",
    "Red kite": "Milvus milvus",
    "Red maple": "Acer rubrum",
    "Red panda": "Ailurus fulgens",
    "Red squirrel": "Sciurus vulgaris",
    "Red-backed salamander": "Plethodon cinereus",
    "Red-eared slider": "Trachemys scripta elegans",
    "Red-eyed tree frog": "Agalychnis callidryas",
    "Red-footed tortoise": "Chelonoidis carbonaria",
    "Red-spotted newt": "Notophthalmus viridescens",
    "Red-tailed hawk": "Buteo jamaicensis",
    "Redcurrant": "Ribes rubrum",
    "Redstart": "Phoenicurus",
    "Redwood": "Sequoia sempervirens",
    "Reindeer lichen": "Cladonia rangiferina",
    "Reishi": "Ganoderma lingzhi",
    "Remora": "Echeneidae",
    "Reticulated python": "Python reticulatus",
    "Rhamphorhynchus": "Rhamphorhynchus",
    "Rhea": "Rhea",
    "Rhinoceros beetle": "Dynastinae",
    "Rhododendron": "Rhododendron",
    "Rhubarb": "Rheum rhabarbarum",
    "Right whale": "Eubalaena",
    "Ring-necked parakeet": "Psittacula krameri",
    "Ring-tailed lemur": "Lemur catta",
    "Roadrunner": "Geococcyx",
    "Robber fly": "Asilidae",
    "Robin (bird)": "Erithacus rubecula",
    "Rockhopper penguin": "Eudyptes chrysocome",
    "Roe deer": "Capreolus capreolus",
    "Roller (bird)": "Coraciidae",
    "Romaine lettuce": "Lactuca sativa var. longifolia",
    "Romanesco broccoli": "Brassica oleracea var. botrytis",
    "Roridula": "Roridula",
    "Rose": "Rosa",
    "Rose hip": "Rosa",
    "Rosemary": "Salvia rosmarinus",
    "Rosewood": "Dalbergia",
    "Rowan": "Sorbus subg. Sorbus",
    "Royal fern": "Osmunda regalis",
    "Royal palm": "Roystonea",
    "Rubber plant": "Ficus elastica",
    "Rubber tree": "Ficus elastica",
    "Russell's viper": "Daboia russelii",
    "Rutabaga": "Brassica napus rapifera",
    "Sable antelope": "Hippotragus niger",
    "Sacred lotus": "Nelumbo nucifera",
    "Sage": "Salvia officinalis",
    "Saguaro": "Carnegiea gigantea",
    "Saiga antelope": "Saiga tatarica",
    "Sailfish": "Istiophorus",
    "Saltasaurus": "Saltasaurus",
    "Saltwater crocodile": "Crocodylus porosus",
    "Salvia": "Salvia",
    "Sambar deer": "Rusa unicolor",
    "Samphire": "Crithmum maritimum",
    "San Pedro cactus": "Echinopsis pachanoi",
    "Sand cat": "Felis margarita",
    "Sand dollar": "Clypeasteroida",
    "Sandalwood": "Santalum album",
    "Sandpiper": "Scolopacidae",
    "Sapodilla": "Manilkara zapota",
    "Sarcosuchus": "Sarcosuchus",
    "Sargassum": "Sargassum",
    "Sarracenia": "Sarracenia",
    "Sassafras": "Sassafras",
    "Satin pothos": "Scindapsus pictus",
    "Satsuma": "Citrus unshiu",
    "Savoy cabbage": "Brassica oleracea var. sabauda",
    "Saw-scaled viper": "Echis",
    "Sawfish": "Pristidae",
    "Scallop": "Pectinidae",
    "Scarab beetle": "Scarabaeidae",
    "Scarlet macaw": "Ara macao",
    "Schefflera": "Schefflera",
    "Scilla": "Scilla",
    "Scorpion": "Scorpiones",
    "Scotch bonnet (pepper)": "Capsicum chinense",
    "Scots pine": "Pinus sylvestris",
    "Screech owl": "Megascops",
    "Sea anemone": "Actiniaria",
    "Sea buckthorn": "Hippophae rhamnoides",
    "Sea cucumber": "Holothuroidea",
    "Sea fan": "Gorgoniidae",
    "Sea lion": "Otariinae",
    "Sea otter": "Enhydra lutris",
    "Sea pen": "Pennatulacea",
    "Sea slug": "Nudibranchia",
    "Sea snake": "Hydrophiinae",
    "Sea sponge": "Porifera",
    "Sea squirt": "Ascidiacea",
    "Sea turtle": "Chelonioidea",
    "Sea urchin": "Echinoidea",
    "Seagrass": "Zosteraceae",
    "Seahorse": "Hippocampus",
    "Seaweed": "Phaeophyceae",
    "Secretary bird": "Sagittarius serpentarius",
    "Sedum": "Sedum",
    "Sei whale": "Balaenoptera borealis",
    "Selaginella": "Selaginella",
    "Sempervivum": "Sempervivum",
    "Senecio": "Senecio",
    "Sequoia": "Sequoia",
    "Serval": "Leptailurus serval",
    "Shallot": "Allium ascalonicum",
    "Shearwater": "Procellariidae",
    "Sheet moss": "Hypnum curvifolium",
    "Shield bug": "Pentatomidae",
    "Shiitake": "Lentinula edodes",
    "Short-eared owl": "Asio flammeus",
    "Shrike": "Laniidae",
    "Sidewinder": "Crotalus cerastes",
    "Sifaka": "Propithecus",
    "Silk moth": "Bombyx mori",
    "Silver birch": "Betula pendula",
    "Silverfish": "Lepisma saccharina",
    "Siskin": "Spinus",
    "Sitka spruce": "Picea sitchensis",
    "Skua": "Stercorariidae",
    "Skunk": "Mephitidae",
    "Skylark": "Alauda arvensis",
    "Slimy salamander": "Plethodon glutinosus",
    "Sloth": "Folivora",
    "Sloth bear": "Melursus ursinus",
    "Slow loris": "Nycticebus",
    "Slow worm": "Anguis fragilis",
    "Smilodon": "Smilodon",
    "Smooth newt": "Lissotriton vulgaris",
    "Snake plant": "Dracaena trifasciata",
    "Snapdragon": "Antirrhinum majus",
    "Snapping turtle": "Chelydridae",
    "Snow leopard": "Panthera uncia",
    "Snow pea": "Pisum sativum var. macrocarpum",
    "Snowdrop": "Galanthus",
    "Snowy owl": "Bubo scandiacus",
    "Softshell turtle": "Trionychidae",
    "Sorrel": "Rumex acetosa",
    "Soursop": "Annona muricata",
    "Spadefoot toad": "Pelobates",
    "Spaghetti squash": "Cucurbita pepo subsp. pepo",
    "Spanish moss": "Tillandsia usneoides",
    "Sparrow": "Passeridae",
    "Spectacled bear": "Tremarctos ornatus",
    "Spectacled caiman": "Caiman crocodilus",
    "Spectacled owl": "Pulsatrix perspicillata",
    "Sperm whale": "Physeter macrocephalus",
    "Sphagnum": "Sphagnum",
    "Spider crab": "Majoidea",
    "Spider monkey": "Ateles",
    "Spider plant": "Chlorophytum comosum",
    "Spinach": "Spinacia oleracea",
    "Spinosaurus": "Spinosaurus",
    "Spoonbill": "Platalea",
    "Spotted salamander": "Ambystoma maculatum",
    "Spring onion": "Allium fistulosum",
    "Spring peeper": "Pseudacris crucifer",
    "Spring salamander": "Gyrinophilus porphyriticus",
    "Springbok": "Antidorcas marsupialis",
    "Spruce": "Picea",
    "St John's wort": "Hypericum perforatum",
    "Stag beetle": "Lucanidae",
    "Staghorn coral": "Acropora cervicornis",
    "Staghorn fern": "Platycerium",
    "Stapelia": "Stapelia",
    "Star cactus": "Astrophytum asteria",
    "Starfish": "Asteroidea",
    "Starfruit": "Averrhoa carambola",
    "Starfruit tree": "Averrhoa carambola",
    "Starling": "Sturnidae",
    "Stegosaurus": "Stegosaurus",
    "Steller's sea eagle": "Haliaeetus pelagicus",
    "Stick insect": "Phasmatodea",
    "Stingray": "Myliobatoidei",
    "Stoat": "Mustela erminea",
    "Stork": "Ciconiidae",
    "Strangler fig": "Ficus",
    "Strawberry": "Fragaria × ananassa",
    "Strawberry poison-dart frog": "Oophaga pumilio",
    "String of hearts": "Ceropegia woodii",
    "String of pearls": "Curio rowleyanus",
    "Stygimoloch": "Stygimoloch",
    "Styracosaurus": "Styracosaurus",
    "Sugar glider": "Petaurus breviceps",
    "Sugar maple": "Acer saccharum",
    "Sugar snap pea": "Pisum sativum var. macrocarpum",
    "Sulcata tortoise": "Centrochelys sulcata",
    "Sulphur-crested cockatoo": "Cacatua galerita",
    "Sumatran rhinoceros": "Dicerorhinus sumatrensis",
    "Sun bear": "Helarctos malayanus",
    "Sun conure": "Aratinga solstitialis",
    "Sunbird": "Nectariniidae",
    "Sunda clouded leopard": "Neofelis diardi",
    "Sundew": "Drosera",
    "Sunfish (Mola mola)": "Mola mola",
    "Sunflower": "Helianthus annuus",
    "Surgeonfish": "Acanthuridae",
    "Surinam toad": "Pipa pipa",
    "Swallow": "Hirundinidae",
    "Swallowtail butterfly": "Papilionidae",
    "Swan": "Cygnus",
    "Sweat bee": "Halictidae",
    "Sweet William": "Dianthus barbatus",
    "Sweet pea": "Lathyrus odoratus",
    "Sweet potato": "Ipomoea batatas",
    "Sweetgum": "Liquidambar styraciflua",
    "Swift": "Apodidae",
    "Swiss chard": "Beta vulgaris subsp. vulgaris",
    "Swiss cheese plant": "Monstera deliciosa",
    "Sword fern": "Nephrolepis",
    "Swordfish": "Xiphias gladius",
    "Sycamore": "Platanus",
    "Taipan": "Oxyuranus",
    "Tallipot palm": "Corypha umbraculifera",
    "Tamarind": "Tamarindus indica",
    "Tanager": "Thraupidae",
    "Tangerine": "Citrus ×tangerina",
    "Tapir": "Tapiridae",
    "Tarantula": "Theraphosidae",
    "Tarantula hawk": "Pepsis",
    "Taro": "Colocasia esculenta",
    "Tarpon": "Megalops",
    "Tarragon": "Artemisia dracunculus",
    "Tarsier": "Tarsiidae",
    "Tasmanian devil": "Sarcophilus harrisii",
    "Tawny frogmouth": "Podargus strigoides",
    "Tawny owl": "Strix aluco",
    "Tea tree": "Melaleuca alternifolia",
    "Teak": "Tectona grandis",
    "Tegu": "Tupinambis",
    "Telegraph plant": "Codariocalyx motorius",
    "Tenontosaurus": "Tenontosaurus",
    "Tern": "Sterninae",
    "Therizinosaurus": "Therizinosaurus",
    "Thistle": "Cirsium",
    "Thorn bug": "Umbonia crassicornis",
    "Thornback ray": "Raja clavata",
    "Thorny devil": "Moloch horridus",
    "Thresher shark": "Alopias",
    "Thrush": "Turdidae",
    "Thyme": "Thymus vulgaris",
    "Tick": "Ixodida",
    "Tiger": "Panthera tigris",
    "Tiger beetle": "Cicindelinae",
    "Tiger salamander": "Ambystoma tigrinum",
    "Tiger shark": "Galeocerdo cuvier",
    "Tillandsia": "Tillandsia",
    "Titan arum": "Amorphophallus titanum",
    "Titan beetle": "Titanus giganteus",
    "Titanosaurus": "Titanosaurus",
    "Tokay gecko": "Gekko gecko",
    "Tomatillo": "Physalis philadelphica",
    "Tomato": "Solanum lycopersicum",
    "Tomato frog": "Dyscophus",
    "Topi": "Damaliscus lunatus jimela",
    "Torch ginger": "Etlingera elatior",
    "Toucan": "Ramphastidae",
    "Tradescantia": "Tradescantia",
    "Tragopan": "Tragopan",
    "Trapdoor spider": "Ctenizidae",
    "Tree fern": "Cyatheales",
    "Tree frog": "Hylidae",
    "Tree-kangaroo": "Dendrolagus",
    "Treecreeper": "Certhiidae",
    "Triceratops": "Triceratops",
    "Trigger plant": "Stylidium",
    "Triggerfish": "Balistidae",
    "Trogon": "Trogonidae",
    "Truffle": "Tuber",
    "Tuatara": "Sphenodon",
    "Tulip": "Tulipa",
    "Tulip tree": "Liriodendron",
    "Tuna": "Thunnini",
    "Turaco": "Musophagidae",
    "Turkey (bird)": "Meleagris",
    "Turkey vulture": "Cathartes aura",
    "Turmeric": "Curcuma longa",
    "Turnip": "Brassica rapa subsp. rapa",
    "Tyrannosaurus": "Tyrannosaurus",
    "Ugli fruit": "Citrus × tangelo",
    "Umbrella bird": "Cephalopterus",
    "Utahraptor": "Utahraptor",
    "Valerian": "Valeriana officinalis",
    "Vampire bat": "Desmodontinae",
    "Velociraptor": "Velociraptor",
    "Velvet ant": "Mutillidae",
    "Velvet mite": "Trombidiidae",
    "Venus flytrap": "Dionaea muscipula",
    "Verbena": "Verbena",
    "Verreaux's eagle": "Aquila verreauxii",
    "Vervet monkey": "Chlorocebus pygerythrus",
    "Victoria amazonica": "Victoria amazonica",
    "Vietnamese mossy frog": "Theloderma corticale",
    "Vine snake": "Ahaetulla",
    "Violet (plant)": "Viola",
    "Viperfish": "Chauliodus",
    "Vireo": "Vireonidae",
    "Viscacha": "Lagidium",
    "Wagtail": "Motacilla",
    "Wakame": "Undaria pinnatifida",
    "Wallaby": "Macropodidae",
    "Wallace's flying frog": "Rhacophorus nigropalmatus",
    "Walnut tree": "Juglans",
    "Walrus": "Odobenus rosmarus",
    "Warbler": "Sylviidae",
    "Wasabi": "Eutrema japonicum",
    "Water buffalo": "Bubalus bubalis",
    "Water chestnut": "Eleocharis dulcis",
    "Water hemlock": "Cicuta",
    "Water hyacinth": "Pontederia crassipes",
    "Water lettuce": "Pistia stratiotes",
    "Water lily": "Nymphaeaceae",
    "Water monitor": "Varanus salvator",
    "Water strider": "Gerridae",
    "Waterbuck": "Kobus ellipsiprymnus",
    "Watercress": "Nasturtium officinale",
    "Watermelon": "Citrullus lanatus",
    "Waterwheel plant": "Aldrovanda vesiculosa",
    "Waxwing": "Bombycilla",
    "Waxy monkey tree frog": "Phyllomedusa sauvagii",
    "Weasel": "Mustela",
    "Weaver ant": "Oecophylla",
    "Wedge-tailed eagle": "Aquila audax",
    "Weedy seadragon": "Phyllopteryx taeniolatus",
    "Weeping willow": "Salix babylonica",
    "Weevil": "Curculionoidea",
    "Welwitschia": "Welwitschia mirabilis",
    "Weta": "Anostostomatidae",
    "Whale louse": "Cyamidae",
    "Whale shark": "Rhincodon typus",
    "Whip scorpion": "Thelyphonida",
    "Whirligig beetle": "Gyrinidae",
    "Whisk fern": "Psilotum",
    "White rhinoceros": "Ceratotherium simum",
    "White snakeroot": "Ageratina altissima",
    "White's tree frog": "Litoria caerulea",
    "White-tailed eagle": "Haliaeetus albicilla",
    "Whitetip reef shark": "Triaenodon obesus",
    "Wild garlic": "Allium ursinum",
    "Wildebeest": "Connochaetes",
    "Willow": "Salix",
    "Winter jasmine": "Jasminum nudiflorum",
    "Wisteria": "Wisteria",
    "Witch hazel": "Hamamelis",
    "Wobbegong": "Orectolobidae",
    "Wolf": "Canis lupus",
    "Wolf spider": "Lycosidae",
    "Wolfsbane": "Aconitum",
    "Wollemi pine": "Wollemia nobilis",
    "Wolverine": "Gulo gulo",
    "Wombat": "Vombatidae",
    "Wood frog": "Lithobates sylvaticus",
    "Woodlouse": "Oniscidea",
    "Woodpecker": "Picidae",
    "Woolly mammoth": "Mammuthus primigenius",
    "Wrasse": "Labridae",
    "Wren": "Troglodytidae",
    "Yak": "Bos grunniens",
    "Yam": "Dioscorea",
    "Yarrow": "Achillea millefolium",
    "Yellow jacket": "Vespula",
    "Yew": "Taxus",
    "Yucca": "Yucca",
    "Yuzu": "Citrus ×junos",
    "ZZ plant": "Zamioculcas zamiifolia",
    "Zebra": "Hippotigris",
    "Zebra plant": "Aphelandra squarrosa",
    "Zinnia": "Zinnia",
    "Zucchini": "Cucurbita pepo var. cylindrica",
}
